"""File browsing with safe path resolution and type detection (v2)."""
from __future__ import annotations

import fnmatch
import os
import stat
import time
from typing import Dict, List, Optional, Tuple

from app.config import config


EXT_MAP = {
    ".md": "markdown",
    ".pdf": "pdf",
    ".png": "image",
    ".jpg": "image",
    ".jpeg": "image",
    ".gif": "image",
    ".svg": "image",
    ".webp": "image",
    ".csv": "data",
    ".txt": "text",
    ".zip": "archive",
    ".tar": "archive",
    ".gz": "archive",
    ".bz2": "archive",
    ".xz": "archive",
    ".py": "code",
    ".ipynb": "code",
    ".cpp": "code",
    ".h": "code",
    ".hpp": "code",
    ".c": "code",
    ".cc": "code",
    ".json": "data",
    ".yaml": "data",
    ".yml": "data",
    ".xml": "data",
    ".html": "web",
    ".css": "web",
    ".js": "code",
    ".ts": "code",
    ".log": "text",
    ".bag": "rosbag",
    ".launch": "ros",
    ".urdf": "ros",
    ".sdf": "ros",
    ".pcd": "pointcloud",
    ".ply": "pointcloud",
    ".stl": "mesh",
    ".obj": "mesh",
}

PREVIEW_EXTS = (
    ".md",
    ".pdf",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".webp",
    ".txt",
    ".csv",
    ".log",
    ".py",
    ".cpp",
    ".h",
    ".hpp",
    ".c",
    ".json",
    ".yaml",
    ".yml",
    ".xml",
    ".html",
    ".css",
    ".js",
)


def _sync_source_roots() -> List[str]:
    """Real paths of configured external sync directories."""
    roots = []
    for src in config.get("sync_dirs", {}).values():
        real = os.path.realpath(src)
        if os.path.isdir(real):
            roots.append(real)
    return roots


def _is_within(path: str, root: str) -> bool:
    return path == root or path.startswith(root + os.sep)


def _is_allowed_symlink_dir(full: str, root_dir: str) -> bool:
    """Only follow symlinks that point into the root or a configured sync dir."""
    if not os.path.islink(full):
        return True
    real = os.path.realpath(full)
    allowed = [os.path.realpath(root_dir)] + _sync_source_roots()
    return any(_is_within(real, r) for r in allowed)


def resolve_safe_path(root_dir: str, request_path: str) -> Tuple[Optional[str], Optional[str]]:
    """Resolve ``request_path`` against ``root_dir``.

    Returns ``(abs_path, None)`` on success or ``(None, error_message)`` on
    failure. Symlinks are checked with ``realpath``: only links that stay inside
    the root or point into a configured ``sync_dirs`` source are allowed.
    """
    if request_path is None:
        request_path = ""
    try:
        clean = str(request_path).lstrip("/")
        if "\x00" in clean:
            return None, "非法路径"
        abs_path = os.path.abspath(os.path.join(root_dir, clean))
        abs_real = os.path.realpath(abs_path)
    except (ValueError, OSError):
        return None, "路径解析失败"

    root_abs = os.path.abspath(root_dir)
    root_real = os.path.realpath(root_dir)

    # Keep the *logical* path inside the served root so links generated by the UI
    # stay as /browse/<alias>/... and don't leak real filesystem locations.
    if abs_path != root_abs and not abs_path.startswith(root_abs + os.sep):
        return None, "路径超出允许目录"

    allowed_real = [root_real] + _sync_source_roots()
    if not any(_is_within(abs_real, r) for r in allowed_real):
        return None, "路径超出允许目录"
    if not os.path.exists(abs_real):
        return None, "路径不存在"
    return abs_path, None


def _is_hidden(name: str) -> bool:
    return name.startswith(".")


def _matches_any(name: str, patterns: List[str]) -> bool:
    for pattern in patterns:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


# 图片扩展名（由 EXT_MAP 派生，避免两处维护）
IMAGE_EXTS = tuple(k for k, v in EXT_MAP.items() if v == "image")

# 文件类型 → 图标（列表/搜索结果统一使用，避免每处硬编码）
TYPE_ICONS = {
    "directory": "\U0001F4C1",   # 📁
    "markdown":  "\U0001F4DD",   # 📝
    "pdf":       "\U0001F4D5",   # 📕
    "image":     "\U0001F5BC",   # 🖼
    "text":      "\U0001F4C4",   # 📄
    "code":      "\u2328",       # ⌨
    "data":      "\U0001F4CA",   # 📊
    "archive":   "\U0001F4E6",   # 📦
    "web":       "\U0001F310",   # 🌐
    "ros":       "\U0001F916",   # 🤖
    "rosbag":    "\U0001F916",
    "video":     "\U0001F3AC",   # 🎬
    "audio":     "\U0001F3B5",   # 🎵
    "other":     "\U0001F4C4",
}


def icon_for(entry_type: str) -> str:
    return TYPE_ICONS.get(entry_type, TYPE_ICONS["other"])


def sibling_files(abs_path: str, root_dir: str, exts, limit: int = 400) -> List[Dict]:
    """同目录下指定扩展名的文件列表（按名称排序），用于上一个/下一个导航。"""
    folder = os.path.dirname(abs_path)
    exts = {e.lower() for e in exts}
    try:
        names = sorted(os.listdir(folder), key=lambda n: n.lower())
    except OSError:
        return []
    items = []
    for name in names:
        full = os.path.join(folder, name)
        if not os.path.isfile(full):
            continue
        if os.path.splitext(name)[1].lower() not in exts:
            continue
        items.append({"name": name, "path": os.path.relpath(full, root_dir), "abs": full})
        if len(items) >= limit:
            break
    return items


def sibling_media(abs_path: str, root_dir: str, limit: int = 400) -> List[Dict]:
    """同目录下的图片列表（按名称排序），用于查看器的上一张/下一张导航。"""
    return sibling_files(abs_path, root_dir, IMAGE_EXTS, limit)


def _entry_dict(full: str, root_dir: str, is_dir: bool) -> Optional[Dict]:
    try:
        st = os.stat(full)
    except OSError:
        return None
    rel = os.path.relpath(full, root_dir)
    ext = os.path.splitext(full)[1].lower() if not is_dir else ""
    return {
        "name": os.path.basename(full),
        "path": rel,
        "is_dir": is_dir,
        "size": st.st_size,
        "size_str": human_size(st.st_size),
        "mtime": st.st_mtime,
        "mtime_str": format_time(st.st_mtime),
        "extension": ext,
        "type": get_type_label(is_dir, ext),
        "preview": (not is_dir) and ext in PREVIEW_EXTS,
        "icon": icon_for(get_type_label(is_dir, ext)),
    }


def list_directory(abs_path: str, root_dir: str) -> List[Dict]:
    """List one directory, directories first, then by name."""
    entries = []
    try:
        names = os.listdir(abs_path)
    except (PermissionError, FileNotFoundError):
        return [{"error": "无法读取目录"}]

    for name in names:
        if _is_hidden(name):
            continue
        full = os.path.join(abs_path, name)
        try:
            st = os.stat(full)
        except OSError:
            continue
        is_dir = stat.S_ISDIR(st.st_mode)
        entry = _entry_dict(full, root_dir, is_dir)
        if entry is not None:
            entries.append(entry)

    entries.sort(key=lambda e: (not e["is_dir"], e["name"].lower()))
    return entries


def get_file_info(abs_path: str, root_dir: str) -> Optional[Dict]:
    """Info dict for a single file/directory."""
    try:
        st = os.stat(abs_path)
    except OSError:
        return None
    is_dir = stat.S_ISDIR(st.st_mode)
    return _entry_dict(abs_path, root_dir, is_dir)


def _walk_filtered(root_dir: str):
    """Yield (full_path, rel_path, is_dir) walking the root with excludes."""
    exclude_dirs = set(config["search"].get("exclude_dirs", []))
    exclude_patterns = config["search"].get("exclude_patterns", [])
    max_files = config["search"].get("max_files", 50000)
    count = 0

    for root, dirs, files in os.walk(root_dir, followlinks=True):
        dirs[:] = [
            d
            for d in dirs
            if not _is_hidden(d)
            and d not in exclude_dirs
            and not _matches_any(d, exclude_patterns)
            and _is_allowed_symlink_dir(os.path.join(root, d), root_dir)
        ]
        for name in files:
            if _is_hidden(name) or _matches_any(name, exclude_patterns):
                continue
            full = os.path.join(root, name)
            yield full, os.path.relpath(full, root_dir), False
            count += 1
            if count >= max_files:
                return


def search_files(root_dir: str, query: str, limit: Optional[int] = None) -> List[Dict]:
    """Case-insensitive filename search, newest first."""
    if limit is None:
        limit = config["search"].get("max_results", 100)
    query_lower = query.lower()
    results = []
    for full, rel, _ in _walk_filtered(root_dir):
        if query_lower in os.path.basename(full).lower():
            entry = _entry_dict(full, root_dir, False)
            if entry is not None:
                results.append(entry)
            if len(results) >= limit:
                break
    results.sort(key=lambda e: e["mtime"], reverse=True)
    return results[:limit]


# ── 全文内容检索（借鉴 Pagefind / copyparty 的静态检索思路）────────────────────
# 说明：中文无需分词——直接用大小写不敏感的子串匹配即可；文本按 (mtime, size)
# 缓存于内存，重复检索只需重读变更过的文件。

_TEXT_CACHE: Dict[str, Tuple[float, int, str]] = {}
_TEXT_CACHE_LIMIT = 3000

DEFAULT_TEXT_EXTS = (
    ".md", ".markdown", ".txt", ".tex", ".rst", ".org",
    ".csv", ".tsv", ".json", ".yaml", ".yml", ".toml", ".ini", ".cfg",
    ".py", ".sh", ".bash", ".js", ".ts", ".html", ".css",
    ".bib", ".log", ".mmd", ".drawio", ".sql",
)


def _text_extensions():
    exts = config.get("search", {}).get("content_extensions") or DEFAULT_TEXT_EXTS
    return {str(e).lower() for e in exts}


def _read_text_cached(full: str, st, max_bytes: int):
    hit = _TEXT_CACHE.get(full)
    if hit is not None and hit[0] == st.st_mtime and hit[1] == st.st_size:
        return hit[2]
    try:
        with open(full, "r", encoding="utf-8", errors="replace") as fh:
            text = fh.read(max_bytes)
    except OSError:
        return None
    if len(_TEXT_CACHE) >= _TEXT_CACHE_LIMIT:
        _TEXT_CACHE.clear()
    _TEXT_CACHE[full] = (st.st_mtime, st.st_size, text)
    return text


def search_content(
    root_dir: str,
    query: str,
    limit_files: Optional[int] = None,
    max_per_file: int = 3,
    context: int = 70,
) -> List[Dict]:
    """在文本类文件正文中检索（大小写不敏感子串），返回带上下文的命中片段。

    结果按「命中次数」降序、其次按修改时间降序排列。
    """
    cfg = config.get("search", {})
    if limit_files is None:
        limit_files = cfg.get("content_max_files", 60)
    max_bytes = int(cfg.get("content_max_file_mb", 2) * 1024 * 1024)
    exts = _text_extensions()
    q = query.strip()
    if not q:
        return []
    ql = q.lower()

    results = []
    for full, rel, _ in _walk_filtered(root_dir):
        if os.path.splitext(full)[1].lower() not in exts:
            continue
        try:
            st = os.stat(full)
        except OSError:
            continue
        if st.st_size > max_bytes:
            continue
        text = _read_text_cached(full, st, max_bytes)
        if not text:
            continue
        low = text.lower()
        total = low.count(ql)
        if total == 0:
            continue
        hits = []
        pos = 0
        while len(hits) < max_per_file:
            pos = low.find(ql, pos)
            if pos < 0:
                break
            line_no = low.count("\n", 0, pos) + 1
            line_start = low.rfind("\n", 0, pos) + 1
            line_end = low.find("\n", pos)
            if line_end < 0:
                line_end = len(text)
            raw = text[line_start:line_end]
            off = pos - line_start
            start = max(0, off - context)
            end = min(len(raw), off + len(q) + context)
            hits.append(
                {
                    "line": line_no,
                    "before": ("…" if start > 0 else "") + raw[start:off].lstrip(),
                    "match": raw[off : off + len(q)],
                    "after": raw[off + len(q) : end].rstrip() + ("…" if end < len(raw) else ""),
                }
            )
            pos += len(q)
        entry = _entry_dict(full, root_dir, False)
        if entry is None:
            continue
        entry = dict(entry)
        entry["count"] = total
        entry["hits"] = hits
        entry["ext"] = os.path.splitext(full)[1].lower().lstrip(".")
        results.append(entry)

    results.sort(key=lambda e: (-e["count"], -e.get("mtime", 0)))
    return results[:limit_files]


def get_recent_files(root_dir: str, limit: int = 20) -> List[Dict]:
    """Most recently modified files, newest first."""
    recent = []
    for full, rel, _ in _walk_filtered(root_dir):
        entry = _entry_dict(full, root_dir, False)
        if entry is not None:
            recent.append(entry)
    recent.sort(key=lambda e: e["mtime"], reverse=True)
    return recent[:limit]


def get_type_label(is_dir: bool, ext: str) -> str:
    if is_dir:
        return "directory"
    return EXT_MAP.get(ext, "file")


def can_preview(ext: str) -> bool:
    return ext in PREVIEW_EXTS


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            if unit == "B":
                return f"{int(value)} B"
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def format_time(ts: float) -> str:
    return time.strftime("%Y-%m-%d %H:%M", time.localtime(ts))

